server {
    server_name akhrots.com www.akhrots.com;

    root /var/www/akhrots;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.mp4$ {
        mp4;
        mp4_buffer_size 1m;
        mp4_max_buffer_size 5m;
        expires max;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/akhrots.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/akhrots.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.akhrots.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = akhrots.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name akhrots.com www.akhrots.com;
    return 404; # managed by Certbot
}
